


#[derive(Clone, Copy, Debug)]
pub enum ObjectType {
    Any,
    /// Placeholder for a function/callback argument
    Function,
    /// Placeholder for a string-like argument
    String,
    /// Placeholder for a number-like argument
    Number,
    /// Placeholder for an object-like argument
    Object,
}

pub struct StaticPropertySig {
    pub is_method: bool,
    pub name: &'static str,
    pub args: &'static [ObjectType],
}

pub const STATIC_PROPERTIES: &[StaticPropertySig] = &[
    // Object / Object.prototype
    StaticPropertySig { is_method: false, name: "__proto__", args: &[] },
    StaticPropertySig { is_method: false, name: "constructor", args: &[] },
    StaticPropertySig { is_method: true,  name: "toString", args: &[] },
    StaticPropertySig { is_method: true,  name: "valueOf", args: &[] },
    StaticPropertySig { is_method: true,  name: "hasOwnProperty", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "isPrototypeOf", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "propertyIsEnumerable", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "__defineGetter__", args: &[ObjectType::String, ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "__defineSetter__", args: &[ObjectType::String, ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "__lookupGetter__", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "__lookupSetter__", args: &[ObjectType::String] },

    // Function / Function.prototype
    StaticPropertySig { is_method: true,  name: "apply", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "bind", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "call", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "toString", args: &[] },
    StaticPropertySig { is_method: false, name: "length", args: &[] },
    StaticPropertySig { is_method: false, name: "name", args: &[] },
    StaticPropertySig { is_method: false, name: "arguments", args: &[] },
    StaticPropertySig { is_method: false, name: "caller", args: &[] },

    // Array / Array.prototype
    StaticPropertySig { is_method: false, name: "length", args: &[] },
    StaticPropertySig { is_method: true,  name: "push", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "pop", args: &[] },
    StaticPropertySig { is_method: true,  name: "shift", args: &[] },
    StaticPropertySig { is_method: true,  name: "unshift", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "splice", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "slice", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "concat", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "indexOf", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "lastIndexOf", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "includes", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "find", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "findIndex", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "filter", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "map", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "reduce", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "reduceRight", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "every", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "some", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "join", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "reverse", args: &[] },
    StaticPropertySig { is_method: true,  name: "sort", args: &[] },
    StaticPropertySig { is_method: true,  name: "keys", args: &[] },
    StaticPropertySig { is_method: true,  name: "values", args: &[] },
    StaticPropertySig { is_method: true,  name: "entries", args: &[] },
    StaticPropertySig { is_method: true,  name: "copyWithin", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "fill", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "flat", args: &[] },
    StaticPropertySig { is_method: true,  name: "flatMap", args: &[ObjectType::Function] },

    // String / String.prototype
    StaticPropertySig { is_method: true,  name: "charAt", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "charCodeAt", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "codePointAt", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "concat", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "includes", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "endsWith", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "startsWith", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "indexOf", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "lastIndexOf", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "match", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "matchAll", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "normalize", args: &[] },
    StaticPropertySig { is_method: true,  name: "padEnd", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "padStart", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "repeat", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "replace", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "replaceAll", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "slice", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "split", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "substr", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "substring", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "toLowerCase", args: &[] },
    StaticPropertySig { is_method: true,  name: "toUpperCase", args: &[] },
    StaticPropertySig { is_method: true,  name: "trim", args: &[] },
    StaticPropertySig { is_method: true,  name: "trimStart", args: &[] },
    StaticPropertySig { is_method: true,  name: "trimEnd", args: &[] },
    StaticPropertySig { is_method: true,  name: "anchor", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "big", args: &[] },
    StaticPropertySig { is_method: true,  name: "blink", args: &[] },
    StaticPropertySig { is_method: true,  name: "bold", args: &[] },
    StaticPropertySig { is_method: true,  name: "fixed", args: &[] },
    StaticPropertySig { is_method: true,  name: "fontcolor", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "fontsize", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "italics", args: &[] },
    StaticPropertySig { is_method: true,  name: "link", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "small", args: &[] },
    StaticPropertySig { is_method: true,  name: "strike", args: &[] },
    StaticPropertySig { is_method: true,  name: "sub", args: &[] },
    StaticPropertySig { is_method: true,  name: "sup", args: &[] },

    // Number / Number.prototype
    StaticPropertySig { is_method: true,  name: "toExponential", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "toFixed", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "toPrecision", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "toString", args: &[] },
    StaticPropertySig { is_method: true,  name: "valueOf", args: &[] },

    // Boolean / Boolean.prototype
    StaticPropertySig { is_method: true,  name: "toString", args: &[] },
    StaticPropertySig { is_method: true,  name: "valueOf", args: &[] },

    // Math (static, but useful)
    StaticPropertySig { is_method: true,  name: "abs", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "acos", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "acosh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "asin", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "asinh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "atan", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "atan2", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "atanh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "cbrt", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "ceil", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "clz32", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "cos", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "cosh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "exp", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "expm1", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "floor", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "fround", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "hypot", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "imul", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "log", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "log10", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "log1p", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "log2", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "max", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "min", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "pow", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "random", args: &[] },
    StaticPropertySig { is_method: true,  name: "round", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "sign", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "sin", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "sinh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "sqrt", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "tan", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "tanh", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "trunc", args: &[ObjectType::Number] },

    // Date / Date.prototype
    StaticPropertySig { is_method: true,  name: "getDate", args: &[] },
    StaticPropertySig { is_method: true,  name: "getDay", args: &[] },
    StaticPropertySig { is_method: true,  name: "getFullYear", args: &[] },
    StaticPropertySig { is_method: true,  name: "getHours", args: &[] },
    StaticPropertySig { is_method: true,  name: "getMilliseconds", args: &[] },
    StaticPropertySig { is_method: true,  name: "getMinutes", args: &[] },
    StaticPropertySig { is_method: true,  name: "getMonth", args: &[] },
    StaticPropertySig { is_method: true,  name: "getSeconds", args: &[] },
    StaticPropertySig { is_method: true,  name: "getTime", args: &[] },
    StaticPropertySig { is_method: true,  name: "getTimezoneOffset", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCDate", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCDay", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCFullYear", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCHours", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCMilliseconds", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCMinutes", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCMonth", args: &[] },
    StaticPropertySig { is_method: true,  name: "getUTCSeconds", args: &[] },
    StaticPropertySig { is_method: true,  name: "setDate", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setFullYear", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setHours", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setMilliseconds", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setMinutes", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setMonth", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setSeconds", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setTime", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCDate", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCFullYear", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCHours", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCMilliseconds", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCMinutes", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCMonth", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setUTCSeconds", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "toDateString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toISOString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toJSON", args: &[] },
    StaticPropertySig { is_method: true,  name: "toLocaleDateString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toLocaleString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toLocaleTimeString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toTimeString", args: &[] },
    StaticPropertySig { is_method: true,  name: "toUTCString", args: &[] },

    // RegExp / RegExp.prototype
    StaticPropertySig { is_method: true,  name: "exec", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "test", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "compile", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: false, name: "flags", args: &[] },
    StaticPropertySig { is_method: false, name: "dotAll", args: &[] },
    StaticPropertySig { is_method: false, name: "global", args: &[] },
    StaticPropertySig { is_method: false, name: "ignoreCase", args: &[] },
    StaticPropertySig { is_method: false, name: "multiline", args: &[] },
    StaticPropertySig { is_method: false, name: "source", args: &[] },
    StaticPropertySig { is_method: false, name: "sticky", args: &[] },
    StaticPropertySig { is_method: false, name: "unicode", args: &[] },

    // JSON (static)
    StaticPropertySig { is_method: true,  name: "parse", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "stringify", args: &[ObjectType::Any] },

    // Promise / Promise.prototype
    StaticPropertySig { is_method: true,  name: "then", args: &[ObjectType::Function, ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "catch", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "finally", args: &[ObjectType::Function] },

    // Map / Map.prototype
    StaticPropertySig { is_method: true,  name: "set", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "get", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "has", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "delete", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "clear", args: &[] },
    StaticPropertySig { is_method: true,  name: "keys", args: &[] },
    StaticPropertySig { is_method: true,  name: "values", args: &[] },
    StaticPropertySig { is_method: true,  name: "entries", args: &[] },
    StaticPropertySig { is_method: true,  name: "forEach", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "size", args: &[] },

    // Set / Set.prototype
    StaticPropertySig { is_method: true,  name: "add", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "has", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "delete", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "clear", args: &[] },
    StaticPropertySig { is_method: true,  name: "keys", args: &[] },
    StaticPropertySig { is_method: true,  name: "values", args: &[] },
    StaticPropertySig { is_method: true,  name: "entries", args: &[] },
    StaticPropertySig { is_method: true,  name: "forEach", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "size", args: &[] },

    // WeakMap / WeakSet (only a few)
    StaticPropertySig { is_method: true,  name: "set", args: &[ObjectType::Object, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "get", args: &[ObjectType::Object] },
    StaticPropertySig { is_method: true,  name: "has", args: &[ObjectType::Object] },
    StaticPropertySig { is_method: true,  name: "delete", args: &[ObjectType::Object] },
    StaticPropertySig { is_method: true,  name: "add", args: &[ObjectType::Object] },

    // Symbol / Symbol.prototype
    StaticPropertySig { is_method: false, name: "description", args: &[] },
    StaticPropertySig { is_method: true,  name: "toString", args: &[] },
    StaticPropertySig { is_method: true,  name: "valueOf", args: &[] },

    // Typed arrays (shared subset)
    StaticPropertySig { is_method: false, name: "buffer", args: &[] },
    StaticPropertySig { is_method: false, name: "byteLength", args: &[] },
    StaticPropertySig { is_method: false, name: "byteOffset", args: &[] },
    StaticPropertySig { is_method: false, name: "length", args: &[] },
    StaticPropertySig { is_method: true,  name: "set", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "subarray", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "copyWithin", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "entries", args: &[] },
    StaticPropertySig { is_method: true,  name: "every", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "fill", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "filter", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "find", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "findIndex", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "forEach", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "includes", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "indexOf", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "join", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "keys", args: &[] },
    StaticPropertySig { is_method: true,  name: "lastIndexOf", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "map", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "reduce", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "reduceRight", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "reverse", args: &[] },
    StaticPropertySig { is_method: true,  name: "slice", args: &[ObjectType::Number, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "some", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "sort", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "values", args: &[] },

    // Error / Error.prototype
    StaticPropertySig { is_method: false, name: "name", args: &[] },
    StaticPropertySig { is_method: false, name: "message", args: &[] },
    StaticPropertySig { is_method: false, name: "stack", args: &[] },

    // Console (common)
    StaticPropertySig { is_method: true,  name: "log", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "info", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "warn", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "error", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "debug", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "trace", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "table", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "group", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "groupCollapsed", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "groupEnd", args: &[] },
    StaticPropertySig { is_method: true,  name: "time", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "timeEnd", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "timeLog", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "clear", args: &[] },
    StaticPropertySig { is_method: true,  name: "count", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "countReset", args: &[ObjectType::String] },
    StaticPropertySig { is_method: true,  name: "dir", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "dirxml", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "assert", args: &[ObjectType::Any] },

    // DOM-like properties (generic)
    StaticPropertySig { is_method: false, name: "innerHTML", args: &[] },
    StaticPropertySig { is_method: false, name: "outerHTML", args: &[] },
    StaticPropertySig { is_method: false, name: "textContent", args: &[] },
    StaticPropertySig { is_method: false, name: "innerText", args: &[] },
    StaticPropertySig { is_method: false, name: "outerText", args: &[] },
    StaticPropertySig { is_method: false, name: "className", args: &[] },
    StaticPropertySig { is_method: false, name: "classList", args: &[] },
    StaticPropertySig { is_method: false, name: "id", args: &[] },
    StaticPropertySig { is_method: false, name: "style", args: &[] },
    StaticPropertySig { is_method: false, name: "dataset", args: &[] },
    StaticPropertySig { is_method: false, name: "children", args: &[] },
    StaticPropertySig { is_method: false, name: "firstChild", args: &[] },
    StaticPropertySig { is_method: false, name: "lastChild", args: &[] },
    StaticPropertySig { is_method: false, name: "parentNode", args: &[] },
    StaticPropertySig { is_method: false, name: "parentElement", args: &[] },
    StaticPropertySig { is_method: false, name: "previousSibling", args: &[] },
    StaticPropertySig { is_method: false, name: "nextSibling", args: &[] },
    StaticPropertySig { is_method: true,  name: "appendChild", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "removeChild", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "insertBefore", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "replaceChild", args: &[ObjectType::Any, ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "addEventListener", args: &[ObjectType::String, ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "removeEventListener", args: &[ObjectType::String, ObjectType::Function] },
    StaticPropertySig { is_method: true,  name: "dispatchEvent", args: &[ObjectType::Object] },

    // Window / global-ish
    StaticPropertySig { is_method: true,  name: "setTimeout", args: &[ObjectType::Function, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "setInterval", args: &[ObjectType::Function, ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "clearTimeout", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "clearInterval", args: &[ObjectType::Number] },
    StaticPropertySig { is_method: true,  name: "alert", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "confirm", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "prompt", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: false, name: "location", args: &[] },
    StaticPropertySig { is_method: false, name: "navigator", args: &[] },
    StaticPropertySig { is_method: false, name: "document", args: &[] },
    StaticPropertySig { is_method: false, name: "localStorage", args: &[] },
    StaticPropertySig { is_method: false, name: "sessionStorage", args: &[] },
    StaticPropertySig { is_method: true,  name: "fetch", args: &[ObjectType::Any] },
    StaticPropertySig { is_method: true,  name: "XMLHttpRequest", args: &[] },

    // Misc random property-ish names (useful for fuzzing)
    StaticPropertySig { is_method: false, name: "foo", args: &[] },
    StaticPropertySig { is_method: false, name: "bar", args: &[] },
    StaticPropertySig { is_method: false, name: "baz", args: &[] },
    StaticPropertySig { is_method: false, name: "qux", args: &[] },
    StaticPropertySig { is_method: false, name: "quux", args: &[] },
    StaticPropertySig { is_method: false, name: "data", args: &[] },
    StaticPropertySig { is_method: false, name: "value", args: &[] },
    StaticPropertySig { is_method: false, name: "config", args: &[] },
    StaticPropertySig { is_method: false, name: "options", args: &[] },
    StaticPropertySig { is_method: false, name: "state", args: &[] },
    StaticPropertySig { is_method: false, name: "props", args: &[] },
    StaticPropertySig { is_method: false, name: "callback", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "handler", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "onload", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "onerror", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "onclick", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "onchange", args: &[ObjectType::Function] },
    StaticPropertySig { is_method: false, name: "onsubmit", args: &[ObjectType::Function] },
];

pub fn get_property_list() -> Vec<&'static str> {
    STATIC_PROPERTIES.iter().filter(|sig| sig.is_method == false).map(|sig| sig.name).collect()
}